### PR TITLE
Translated into English

### PR DESCRIPTION
**Pull request by epinox**
I would like to make my contribution to this project and have translated all documentation comments into English. However, since I don't speak Russian, I used a machine translation to assist.

See: Issue https://github.com/saraff-9EB1047A4BEB4cef8506B29BA325BD5A/Saraff.Twain.NET/issues/15

### CODE REVIEW

**Comment by saraff-9EB1047A4BEB4cef8506B29BA325BD5A** [comment]
I think that the first option is better:
```
<summary>
English
<para xml:lang="ru">Russian</para>
</summary>
```

**Comment by epinox** [comment]
It's updated now... I hope I've got it all.

**Comment by saraff-9EB1047A4BEB4cef8506B29BA325BD5A** [comment]
Great job!

**Comment by epinox** [comment]
Nice that you like it... your library is pretty damn useful. Good job too! ;-)

**Pull request merged**
